In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [3]:
df=pd.read_csv("Iris.csv")

In [4]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
31    32            5.4           3.4            1.5           0.4   
32    33            5.2           4.1            1.5           0.1   
33    34            5.5           4.2            1.4           0.2   
34    35            4.9           3.1            1.5           0.1   
35    36            5.0           3.2            1.2           0.2   
36    37            5.5           3.5            1.3           0.2   
37    38            4.9           3.1            1.5           0.1   
38    39            4.4           3.0            1.3           0.2   
39    40            5.1           3.4            1.5           0.2   
40    41            5.0           3.5            1.3           0.3   
41    42            4.5           2.3            1.3           0.3   
42    43            4.4           3.2            1.3           0.2   
43    44            5.0           3.5            1.6           0.6   
44    45            5.1           3.8            1.9           0.4   
45    46            4.8           3.0            1.4           0.3   
46    47            5.1           3.8            1.6           0.2   
47    48            4.6           3.2            1.4           0.2   
48    49            5.3           3.7            1.5           0.2   
49    50            5.0           3.3            1.4           0.2   
50    51            7.0           3.2            4.7           1.4   
51    52            6.4           3.2            4.5           1.5   
52    53            6.9           3.1            4.9           1.5   
53    54            5.5           2.3            4.0           1.3   
54    55            6.5           2.8            4.6           1.5   
55    56            5.7           2.8            4.5           1.3   
56    57        

In [5]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
X=df.drop(columns=['SepalWidthCm','PetalWidthCm','Species'])
y=df['Species']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_test.shape)
print(y_train.shape)

(120, 3)
(30, 3)
(30,)
(120,)


In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

In [18]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score

In [19]:
gb=GaussianNB()
gb.fit(X_train,y_train)

GaussianNB()

In [29]:
gb_predict=gb.predict(X_train)
gb_predict

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
     

In [21]:
print(accuracy_score(y_train,gb_predict))
print(confusion_matrix(y_train,gb_predict))

0.9916666666666667
[[37  0  0]
 [ 0 41  0]
 [ 0  1 41]]


In [24]:
y_train

55     Iris-versicolor
10         Iris-setosa
77     Iris-versicolor
122     Iris-virginica
133     Iris-virginica
49         Iris-setosa
35         Iris-setosa
99     Iris-versicolor
7          Iris-setosa
70     Iris-versicolor
65     Iris-versicolor
74     Iris-versicolor
90     Iris-versicolor
121     Iris-virginica
27         Iris-setosa
104     Iris-virginica
86     Iris-versicolor
68     Iris-versicolor
33         Iris-setosa
57     Iris-versicolor
29         Iris-setosa
97     Iris-versicolor
64     Iris-versicolor
125     Iris-virginica
136     Iris-virginica
59     Iris-versicolor
41         Iris-setosa
51     Iris-versicolor
138     Iris-virginica
100     Iris-virginica
96     Iris-versicolor
82     Iris-versicolor
116     Iris-virginica
114     Iris-virginica
85     Iris-versicolor
111     Iris-virginica
48         Iris-setosa
5          Iris-setosa
128     Iris-virginica
13         Iris-setosa
87     Iris-versicolor
105     Iris-virginica
60     Iris-versicolor
40         